### ISSUE TITLE
Implement forms code/design

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#47]
There are two forms shown in the [Figma design](https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Websites?type=design&node-id=292%3A576&mode=design&t=xQGdY2YGASMQkfdF-1).

### Design Steps:
- [x] Design 1. The form for the home, or the "default alternating black/white theme", looks like material design.
- [ ] Design 2. For other parts of the website, there is a different style. This form style is used in pages and components (filtering, searching, dropdowns).

### Implementation Steps:
- [ ] Link third-party form (possibly for new members).
- [ ] Implement back end for form submission.

[1] Design 1
![Screenshot 2023-12-24 070635](https://github.com/code4sac/opensac.org/assets/6665595/932e6f40-705e-4ba0-8c04-a6df0cffd673)

[2] Design 2
![Screenshot 2023-12-24 070836](https://github.com/code4sac/opensac.org/assets/6665595/71591e4b-b9c5-4b5f-bd71-6c9b91d5ed09)
![Screenshot 2023-12-24 070801](https://github.com/code4sac/opensac.org/assets/6665595/a42b768f-6719-4631-8ba0-f23d81180395)
